# Generated by Django 4.2.17 on 2025-06-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН организации')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Текущий баланс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True, verbose_name='Уникальный ID операции')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма платежа')),
                ('payer_inn', models.CharField(max_length=12, verbose_name='ИНН плательщика')),
                ('document_number', models.CharField(max_length=50, verbose_name='Номер платежного документа')),
                ('document_date', models.DateTimeField(verbose_name='Дата и время документа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'indexes': [models.Index(fields=['operation_id'], name='api_payment_operati_f52926_idx'), models.Index(fields=['payer_inn'], name='api_payment_payer_i_05435e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма изменения')),
                ('old_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Баланс до изменения')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Баланс после изменения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_logs', to='api.organization')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.payment', verbose_name='Связанный платеж')),
            ],
            options={
                'verbose_name': 'Лог баланса',
                'verbose_name_plural': 'Логи баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
